name: Demo Workflow
on: workflow_dispatch
jobs:  
  print:
    runs-on: windows-latest
    steps:
      - name: Print to console
        run: echo Hello Git Actions!
      - name: Print a few lines to console
        run:
          echo First line!
          echo Second line!
